server:
  port: 8080
  
spring:
  application:
    name: gateway
    
# EUREKA DISCOVERY
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka 

# ZUUL
zuul:
  prefix: /api
  ignored-services: '*'   
  
  routes:
    crud:
      path: /crud/**
      service-id: crud
      strip-prefix: false
      custom-sensitive-headers: true
      
      
    pagamento:
      path: /pagamento/**
      service-id: pagamento
      strip-prefix: false
      custom-sensitive-headers: true         